name: Bramil API Pipeline
on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install jq
        run: sudo apt-get install jq

      - name: Read version file and set environment variables
        run: |
          versions=$(cat versions.json)
          echo "$versions" | jq -r 'to_entries | .[] | "MICROSERVICE_\(.key | ascii_upcase)=\(.value)"' >> $GITHUB_ENV  
        
      - name: Build and Push Docker Image Bramil
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: cod4it/gig.bramil:${{ env.MICROSERVICE_BRAMIL }}
          file: Bramil.Dockerfile
      
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.WEPROMOLINK_DEV_HOST }}
          username: ${{ secrets.WEPROMOLINK_DEV_USERNAME }}
          password: ${{ secrets.WEPROMOLINK_DEV_PASSWORD }}
          script:  |
            cd gigs
            cd gigs-bramil/
            git pull
            git checkout master
            cd K8s/
            versions=$(cat ../../versions.json)
            readarray -t versions <<< "$(echo "$versions" | jq -r 'to_entries | .[] | "MICROSERVICE_\(.key | ascii_upcase)=\(.value)"')"; for v in "${versions[@]}"; do export "$v"; done
            envsubst < bramil.yml > bramil_prod_ready.yml
            microk8s kubectl apply -f bramil_prod_ready.yml